### PR TITLE
New micro illustration info bold grey

### PR DESCRIPTION
**Pull request by gongora92**
## Description
New icon

## Testing
New icon should be visible

## Screenshots/Captures
infoBoldGrey

## Checks
- [ ] Requires documentation update
- [x] Requires lib version update

## Versioning impact
- [ ] **MAJOR** incompatible API changes.
- [x] **MINOR** adds functionality in a backwards-compatible manner.
- [ ] **PATCH** backwards-compatible bug fixes.

### CODE REVIEW

**Comment by JoseOrtiz** [comment]
We use to modify the icon color by changing it using css. You could have the same approach by using `InfoIcon` and modify the color
```
.icon {
  path {
    fill: #6B778C;
  }
}
```

**Comment by gongora92** [comment]
> We use to modify the icon color by changing it using css. You could have the same approach by using `InfoIcon` and modify the color
> 
> ```
> .icon {
>   path {
>     fill: #6B778C;
>   }
> }
> ```

So for this there is not needed change? Should I just add this class and use the same icon?

**Comment by JoseOrtiz** [comment]
> > We use to modify the icon color by changing it using css. You could have the same approach by using `InfoIcon` and modify the color
> > ```
> > .icon {
> >   path {
> >     fill: #6B778C;
> >   }
> > }
> > ```
> 
> So for this there is not needed change? Should I just add this class and use the same icon?

I think so, try that approach and let me know

**Comment by gongora92** [comment]
> > > We use to modify the icon color by changing it using css. You could have the same approach by using `InfoIcon` and modify the color
> > > ```
> > > .icon {
> > >   path {
> > >     fill: #6B778C;
> > >   }
> > > }
> > > ```
> > 
> > 
> > So for this there is not needed change? Should I just add this class and use the same icon?
> 
> I think so, try that approach and let me know

It worked, thank you!

**Pull request closed without merging**
