### PR TITLE
Update illustrations

### PR DESCRIPTION
**Pull request by mariocnovoa**
## Description
Update illustrations:
- connectCabify
- promptLocation
- promptPermissions
- promptSelfie
- scanSucccess
- setPin
- successInfo
- successPhone
- workInProgress
- gas
- mopSpinner
- mop

### CODE REVIEW

**Review by rahulpsingh — DISMISSED** [review]

**Review by jasonadt — CHANGES_REQUESTED** [review]
Looks good! However as I mentioned in Slack: each updated SVG tag needs to have `class=“icon”` attribute added to it. 
Also: the version in package.json needs to be bumped (you can ask Jose Camiña for help if needed)
Thanks!

@jantocv after this has been merged: please release a new version for the assets to GH and npm and then prepare a PR for updating b2c-map-ui to use this latest assets version. Thx!

**Review by jantocv — APPROVED** [review]
🎊  congratulations :) job done 💪

**Review by TanMar23 — APPROVED** [review]

**Review by rahulpsingh — APPROVED** [review]

**Comment by jantocv** [comment]
@jasonadt we need your approval here, Thanks!

**Comment by JoseOrtiz** [comment]
Are we controlling icon size?

**Comment by jasonadt** [comment]
> Are we controlling icon size?

Good question, but it’s not the responsibility of this repo (instead: each repo that uses the icons will be responsible for setting the size)

**Review by jasonadt — APPROVED** [review]
Ship it! 👍

**Pull request merged**
